# Generated by Django 4.2.7 on 2023-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zaposleni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra_zaposlenog', models.PositiveIntegerField()),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('strucna_sprema', models.CharField(max_length=100)),
                ('ocjena_zaposlenog', models.FloatField()),
            ],
        ),
    ]
