# Generated by Django 4.2.7 on 2023-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaposlenici', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zaposleni',
            options={'verbose_name_plural': 'Zaposleni'},
        ),
    ]
