# Generated by Django 4.2.7 on 2023-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaposlenici', '0003_remove_zaposleni_datum_rodjenja'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaposleni',
            name='rodjenidan',
            field=models.DateField(default=3232, help_text="Employee's birthdate"),
            preserve_default=False,
        ),
    ]
