# Generated by Django 4.2.7 on 2023-12-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaposlenici', '0004_zaposleni_rodjenidan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaposleni',
            name='rodjenidan',
            field=models.DateField(),
        ),
    ]
