# Generated by Django 4.2.7 on 2023-12-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaposlenici', '0006_alter_zaposleni_rodjenidan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaposleni',
            name='rodjenidan',
        ),
    ]
