# Generated by Django 4.2.7 on 2023-12-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaposlenici', '0007_remove_zaposleni_rodjenidan'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaposleni',
            name='rodjendan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
