# Generated by Django 4.2.7 on 2023-12-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaposlenici', '0008_zaposleni_rodjendan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaposleni',
            name='rodjendan',
        ),
    ]
